# Example configuration for Black.

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# Use [ ] to denote a significant space character.

[tool.black]
line-length = 127 
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''